title: Matt's Coding Blog
author: TheEndIsNear
email: matt.willy@gmail.com     
description: > # this means to ignore newlines until "baseurl:"
  A series of posts describing my journey with elixir and nerves.
  
# social links
twitter_username: ohrwurmat
github_username:  theendisnear

show_excerpts: true # set to false to remove excerpts on the homepage

theme: _minima
